[core]
require-input=false
# Set idle timeout to 0 to disable automatic screen off.
idle-time=0

[output]
name=HDMI-A-1
mode=1920x1080

[launcher]
icon=/usr/share/icons/terminal.png
path=/usr/bin/weston-terminal

[launcher]
icon=/usr/share/icons/browser.png
path=/usr/bin/cog https://www.bilibili.com/