[core]
require-input=false
# Set idle timeout to 0 to disable automatic screen off.
idle-time=0

[output]
name=HDMI-A-1
mode=1920x1080

[shell]
background-image=/usr/share/icons/preview-full.jpg
background-type=scale-crop

[launcher]
icon=/usr/share/icons/terminal-24.png
path=/usr/bin/weston-terminal

[launcher]
icon=/usr/share/icons/bilbil-24.png
path=/usr/bin/cog https://www.bilibili.com/


[launcher]
icon=/usr/share/icons/wifi-24.png
path=/usr/bin/weston-terminal --shell=/usr/bin/wifi_scan

